### ISSUE TITLE
[bug]  Game crashes when NullHooks is injected

### ISSUE THREAD

**Issue by DE-HA** [NullHooks/NullHooks#85]
Game crashes when I inject nulhooks with any injector

Injectors I've tried:

Potato injector
Cozinha injector

**Comment by r4v10l1** [comment]
I know, it is not because of the injector. The last update changed something in the game that broke the cheat, and I really don't know what (I am guessing its a signature or something like that).

The callstack does not show anything useful, but instead shows this, like 5-10 times:

![image](https://user-images.githubusercontent.com/29655971/199722729-ddde1869-efc2-4645-a7d7-5c5f6179ec95.png)

I lost a bit of motivation with the cheat, that's why I don't add new features lately, but I still wanted to fix this.

If anyone knows a possible fix, feel free to comment/PR. I will leave the issue open for now.

**Comment by Utkukck11** [comment]
some sigs have been updated check from osiris

**Comment by Utkukck11** [comment]
well i played on local server for 10 mins i didnt got crash

**Comment by Utkukck11** [comment]
![image](https://user-images.githubusercontent.com/61580513/199818306-0d27ca8a-bdf4-4766-b7eb-489bf8d8fc85.png)
fixed gonna make pr

**Comment by Utkukck11** [comment]
https://github.com/NullHooks/NullHooks/issues/86 here
